### ISSUE TITLE
Error while creating an alert with same summary through UI

### ISSUE THREAD

**Issue by sivtechrepo** [target/goalert#2630]
**Describe the Bug:**
Creating an alert with same summary through UI throws an error and alert is not created 
**Steps to Reproduce:**
1. Create an alert
2. Use the same summary&Details to create an alert
3. While submitting throws an error
**Expected Behavior:**
An alert with the same summary and details should be suppressed through deduplication as it happens in creating an alert through API but in this case, it throws an error

**Observed Behavior:**
Error is thrown as shown below

**Screenshots/Stack Traces:**

**Application Version:**
0.30.0 or earlier versions too
![image](https://user-images.githubusercontent.com/9267000/191801715-402aa24f-16c2-4abf-a7ca-e06e575521bd.png)

`
$ goalert version
...
`

**Desktop:**
 - OS: [e.g. MacOS, Windows]
 - Browser [e.g. Chrome, Safari]

**Smartphone/Tablet:**
 - OS: [e.g. iOS 8.1]
 - Browser [e.g. Chrome, Safari]

**Additional Context:**

**Comment by mastercactapus** [comment]
Interesting, I'm seeing two issues:
- It should add a duplicate suppressed entry into the event log of the original (there is none)
- The UI should probably handle this more gracefully (maybe showing the original alert as de-duplicated)

Confirmed as of 5071dbd2df08ff5c53d187e898d468d76bfdf561

**Comment by sivtechrepo** [comment]
is that been fixed with the changes in the merge request?

**Comment by mastercactapus** [comment]
Still an issue as of 5/23/23
![image](https://github.com/target/goalert/assets/595010/60e7447e-6c1b-4736-940d-7ed0acda55e4)
